#!/usr/bin/env bash
# Start the MCP server using Docker
docker build -t mindriftfall2infinitepiio/bookmark-manager-mcp:v1.0.0 .
claude mcp add bookmark-manager -- docker run \
            --rm \
            --interactive \
            --volume ~/.data:/app/.data \
            mindriftfall2infinitepiio/bookmark-manager-mcp:v1.0.0
