name: Test Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - 'feat/*'
      - 'feature/*'
      - 'fix/*'
      - 'hotfix/*'
      - 'dev/*'

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test Podman build
      uses: redhat-actions/buildah-build@v2
      with:
        image: bookmark-manager-mcp
        tags: test
        containerfiles: ./Containerfile
        platforms: linux/amd64
        
    - name: Test application startup
      run: |
        sudo apt-get update && sudo apt-get install -y podman
        podman build -t bookmark-manager-test .
        timeout 10 podman run --rm bookmark-manager-test || true
        echo "Build test completed successfully"