name: Test Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - 'feat/*'
      - 'feature/*'
      - 'fix/*'
      - 'hotfix/*'
      - 'dev/*'

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Test Docker build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: bookmark-manager-mcp:test
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Test application startup
      run: |
        docker build -t bookmark-manager-test .
        timeout 10 docker run --rm bookmark-manager-test || true
        echo "Build test completed successfully"