name: Build and Push Container Image

on:
  push:
    branches: [ main ]
    paths-ignore:
        - .github/workflows/**
        - README.md
        - SECURITY.md
        - docs/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: redhat-actions/podman-login@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build container image
      id: build
      uses: redhat-actions/buildah-build@v2
      with:
        image: mindriftfall2infinitepiio/bookmark-manager-mcp
        tags: latest
        containerfiles: ./Containerfile
        platforms: linux/amd64,linux/arm64
        
    - name: Push container image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build.outputs.image }}
        tags: ${{ steps.build.outputs.tags }}
        registry: docker.io